/**
 * 管理员 Vue store 相关常量
 * Created by 王佳欣 on 2018/5/3.
 */
// 登录
export const ADMINISTRATOR_LOGIN_REQUEST = 'ADMINISTRATOR_LOGIN_REQUEST';
export const ADMINISTRATOR_LOGIN_SUCCESS = 'ADMINISTRATOR_LOGIN_SUCCESS';
export const ADMINISTRATOR_LOGIN_ERROR = 'ADMINISTRATOR_LOGIN_ERROR';

// 退出
export const ADMINISTRATOR_LOGOUT_REQUEST = 'ADMINISTRATOR_LOGOUT_REQUEST';
export const ADMINISTRATOR_LOGOUT_SUCCESS = 'ADMINISTRATOR_LOGOUT_SUCCESS';
export const ADMINISTRATOR_LOGOUT_ERROR = 'ADMINISTRATOR_LOGOUT_ERROR';

// 创建
export const ADMINISTRATOR_CREATE_REQUEST = 'ADMINISTRATOR_CREATE_REQUEST';
export const ADMINISTRATOR_CREATE_SUCCESS = 'ADMINISTRATOR_CREATE_SUCCESS';
export const ADMINISTRATOR_CREATE_ERROR = 'ADMINISTRATOR_CREATE_ERROR';

// 获取个人信息
export const ADMINISTRATOR_ME_REQUEST = 'ADMINISTRATOR_ME_REQUEST';
export const ADMINISTRATOR_ME_SUCCESS = 'ADMINISTRATOR_ME_SUCCESS';
export const ADMINISTRATOR_ME_ERROR = 'ADMINISTRATOR_ME_ERROR';

// 修改
export const ADMINISTRATOR_UPDATE_REQUEST = 'ADMINISTRATOR_UPDATE_REQUEST';
export const ADMINISTRATOR_UPDATE_SUCCESS = 'ADMINISTRATOR_UPDATE_SUCCESS';
export const ADMINISTRATOR_UPDATE_ERROR = 'ADMINISTRATOR_UPDATE_ERROR';