
/**
 * easyH5
 * Created by 王佳欣 on 2018/5/14.
 */

// 创建
export const EASYH5_CREATE_REQUEST = 'EASYH5_CREATE_REQUEST';
export const EASYH5_CREATE_SUCCESS = 'EASYH5_CREATE_SUCCESS';
export const EASYH5_CREATE_ERROR = 'EASYH5_CREATE_ERROR';

// 获取
export const EASYH5_GET_REQUEST = 'EASYH5_GET_REQUEST';
export const EASYH5_GET_SUCCESS = 'EASYH5_CREATE_SUCCESS';
export const EASYH5_GET_ERROR = 'EASYH5_GET_ERROR';

// 修改
export const EASYH5_UPDATE_REQUEST = 'EASYH5_GET_REQUEST';
export const EASYH5_UPDATE_SUCCESS = 'EASYH5_UPDATE_SUCCESS';
export const EASYH5_UPDATE_ERROR = 'EASYH5_UPDATE_ERROR';


export const EASYH5_ADD_FILE = 'EASYH5_ADD_FILE';

export const EASYH5_REMOVE_FILE = 'EASYH5_REMOVE_FILE';

export const EASYH5_MOVE_UP = 'EASYH5_MOVE_UP';

export const EASYH5_MOVE_DOWN = 'EASYH5_MOVE_DOWN';